services:
  website:
    image: itziksavaia/website
    ports:
      - "5173:5173"

  nginx:
    image: nginx:stable-perl
    ports: 
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - website